#!/usr/bin/env python3
"""Generate a small LVGL v8 ROM font from a TTF/OTF font."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def unique_codepoints(text: str) -> list[int]:
    seen: set[int] = set()
    out: list[int] = []
    for ch in text:
        cp = ord(ch)
        if cp <= 0x7F or ch.isspace() or cp in seen:
            continue
        seen.add(cp)
        out.append(cp)
    return sorted(out)


def pack_4bpp(img: Image.Image) -> bytes:
    pixels = img.load()
    w, h = img.size
    out = bytearray()
    for y in range(h):
        x = 0
        while x < w:
            hi = int(pixels[x, y] / 17) & 0x0F
            lo = 0
            if x + 1 < w:
                lo = int(pixels[x + 1, y] / 17) & 0x0F
            out.append((hi << 4) | lo)
            x += 2
    return bytes(out)


def render_glyph(font: ImageFont.FreeTypeFont, cp: int, ascent: int):
    ch = chr(cp)
    left, top, right, bottom = font.getbbox(ch, anchor="ls")
    width = max(1, right - left)
    height = max(1, bottom - top)
    adv_w = max(1, int(round(font.getlength(ch) * 16)))

    img = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(img)
    draw.text((-left, -top), ch, font=font, fill=255, anchor="ls")
    if img.getbbox() is None:
        return None

    return {
        "cp": cp,
        "adv_w": adv_w,
        "box_w": width,
        "box_h": height,
        "ofs_x": left,
        "ofs_y": -height - top,
        "bitmap": pack_4bpp(img),
    }


def c_array(name: str, data: bytes, indent: str = "    ") -> str:
    lines = [f"static LV_ATTRIBUTE_LARGE_CONST const uint8_t {name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        values = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"{indent}{values},")
    lines.append("};")
    return "\n".join(lines)


def write_font(font_path: Path, out_path: Path, size: int, symbol: str, text: str) -> None:
    font = ImageFont.truetype(str(font_path), size=size)
    ascent, descent = font.getmetrics()
    line_height = ascent + descent
    codepoints = unique_codepoints(text)

    glyphs = []
    bitmaps = bytearray()
    bitmap_index = 0
    for cp in codepoints:
        glyph = render_glyph(font, cp, ascent)
        if glyph is None:
            continue
        glyph["bitmap_index"] = bitmap_index
        glyphs.append(glyph)
        bitmaps += glyph["bitmap"]
        bitmap_index += len(glyph["bitmap"])

    unicode_list = ", ".join(f"0x{g['cp'] - glyphs[0]['cp']:04x}" for g in glyphs)
    dsc_lines = [
        "static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {",
        "    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},",
    ]
    for glyph in glyphs:
        dsc_lines.append(
            "    "
            f"{{.bitmap_index = {glyph['bitmap_index']}, "
            f".adv_w = {glyph['adv_w']}, "
            f".box_w = {glyph['box_w']}, "
            f".box_h = {glyph['box_h']}, "
            f".ofs_x = {glyph['ofs_x']}, "
            f".ofs_y = {glyph['ofs_y']}}}, /* U+{glyph['cp']:04X} */"
        )
    dsc_lines.append("};")

    lv_line_height = size + 2
    lv_base_line = 3

    content = f"""/* Generated by tools/make_lvgl_rom_font.py. */

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
    #include "lvgl.h"
#else
    #include "lvgl.h"
#endif

{c_array("glyph_bitmap", bitmaps)}

static const uint16_t unicode_list_0[] = {{
    {unicode_list}
}};

{chr(10).join(dsc_lines)}

static const lv_font_fmt_txt_cmap_t cmaps[] = {{
    {{
        .range_start = 0x{glyphs[0]['cp']:04x}, .range_length = {glyphs[-1]['cp'] - glyphs[0]['cp'] + 1}, .glyph_id_start = 1,
        .unicode_list = unicode_list_0, .glyph_id_ofs_list = NULL, .list_length = {len(glyphs)}, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }}
}};

#if LV_VERSION_CHECK(8, 0, 0)
static lv_font_fmt_txt_glyph_cache_t cache;
static const lv_font_fmt_txt_dsc_t font_dsc = {{
#else
static lv_font_fmt_txt_dsc_t font_dsc = {{
#endif
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
#if LV_VERSION_CHECK(8, 0, 0)
    .cache = &cache
#endif
}};

extern const lv_font_t lv_font_montserrat_14;

const lv_font_t {symbol} = {{
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {lv_line_height},
    .base_line = {lv_base_line},
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
    .fallback = &lv_font_montserrat_14
}};
"""
    out_path.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {out_path}: {len(glyphs)} glyphs, {len(bitmaps)} bitmap bytes")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("font")
    parser.add_argument("out")
    parser.add_argument("--size", type=int, default=14)
    parser.add_argument("--symbol", default="ui_font_zh_14")
    parser.add_argument("--text", required=True)
    args = parser.parse_args()
    write_font(Path(args.font), Path(args.out), args.size, args.symbol, args.text)


if __name__ == "__main__":
    main()
