from building import *

cwd = GetCurrentDir()

# 把 applications 目录下的所有 .c 文件加入 RT-Thread/SCons 构建。
# CPPPATH = path 表示本目录会作为头文件搜索路径，
# 所以本目录里的 "Lcd.h"、"ui.h"、"my_mqtt.h" 可以被其它文件 include。
src = Glob('*.c')
path = [cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

Return('group')
