webtalk_init -webtalk_dir E:/FPGA_prj/EGo1_prj/ultrasound_meter/ultrasound_meter.sim/sim_1/behav/xsim/xsim.dir/tb_beep_led_alarm_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 26 10:57:33 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "851d5132-f1c1-4cf8-b630-920dcc3c98a9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bbc85fd8fcfc45ad88199bd2350df2d9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12500H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3110 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "850 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6392_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2128810491 -regid "" -xml E:/FPGA_prj/EGo1_prj/ultrasound_meter/ultrasound_meter.sim/sim_1/behav/xsim/xsim.dir/tb_beep_led_alarm_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/FPGA_prj/EGo1_prj/ultrasound_meter/ultrasound_meter.sim/sim_1/behav/xsim/xsim.dir/tb_beep_led_alarm_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/FPGA_prj/EGo1_prj/ultrasound_meter/ultrasound_meter.sim/sim_1/behav/xsim/xsim.dir/tb_beep_led_alarm_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
